server:
  port: 8800
spring:
  application:
    name: SpringCloud02
  datasource:
    url: jdbc:mysql://localhost:3306/users?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
