server:
  port: 8002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#     discovery:
#        cluster-name: HN #集群名字可以自定义
#        namespace: 0432b581-c1f8-4ab7-abe2-74b3f001f0b5 #namespace命名空间环境隔离
#        ephemeral: false #判断是否临时实例
#   针对单个服务的 Ribbon 配置
SpringCloudNaCos01:
    ribbon:
      # 基于配置文件形式的 针对单个服务的 Ribbon 负载均衡策略 NaCosRule优先选择本地集群有可能选中其他集群
      NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
